api/src/main/java/cn/crap/dto/ErrorDto.java
package cn.crap.dto;

import cn.crap.framework.SpringContextHolder;
import cn.crap.service.tool.ProjectCache;

import java.util.Date;

public class ErrorDto {
	private String id;
	private String errorCode;
	private String errorMsg;
	private String projectId;
	private Byte status;
	private Long sequence;

	public void setId(String id){
		this.id=id;
	}
	public String getId(){
		return id;
	}

	public void setErrorCode(String errorCode){
		this.errorCode=errorCode;
	}
	public String getErrorCode(){
		return errorCode;
	}

	public void setErrorMsg(String errorMsg){
		this.errorMsg=errorMsg;
	}
	public String getErrorMsg(){
		return errorMsg;
	}

	public void setProjectId(String projectId){
		this.projectId=projectId;
	}
	public String getProjectId(){
		return projectId;
	}

	public void setStatus(Byte status){
		this.status=status;
	}
	public Byte getStatus(){
		return status;
	}

	public void setSequence(Long sequence){
		this.sequence=sequence;
	}
	public Long getSequence(){
		return sequence;
	}

	public String getProjectName(){
		ProjectCache projectCache = SpringContextHolder.getBean("projectCache", ProjectCache.class);
		return projectCache.get(projectId).getName();
	}

}

api/src/main/java/cn/crap/controller/user/StaticizeController.java
package cn.crap.controller.user;

import cn.crap.adapter.ErrorAdapter;
import cn.crap.adapter.InterfaceAdapter;
import cn.crap.dto.CategoryDto;
import cn.crap.dto.DictionaryDto;
import cn.crap.dto.InterfacePDFDto;
import cn.crap.enu.ArticleType;
import cn.crap.enu.MyError;
import cn.crap.enu.ProjectType;
import cn.crap.framework.JsonResult;
import cn.crap.framework.MyException;
import cn.crap.framework.base.BaseController;
import cn.crap.model.*;
import cn.crap.model.Error;
import cn.crap.query.ArticleQuery;
import cn.crap.query.ErrorQuery;
import cn.crap.query.InterfaceQuery;
import cn.crap.query.ModuleQuery;
import cn.crap.service.ArticleService;
import cn.crap.service.ErrorService;
import cn.crap.service.InterfaceService;
import cn.crap.service.ModuleService;
import cn.crap.utils.*;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import java.io.File;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Controller
@RequestMapping("/user/staticize")
public class StaticizeController extends BaseController{
	@Autowired
	private ModuleService moduleService;
	@Autowired
	private InterfaceService interfaceService;
	@Autowired
	private ErrorService errorService;
	@Autowired
	private ArticleService articleService;

	/**
	 * 静态化错误码列表
	 */
	@RequestMapping("/errorList.do")
	public ModelAndView staticizeError(HttpServletRequest req, @RequestParam String projectId,@RequestParam int currentPage,
			String needStaticizes, @RequestParam String secretKey) throws MyException {
		// 验证是否是非法请求
		if( !settingCache.get(S_SECRETKEY).getValue().equals(secretKey) ){
			throw new MyException(MyError.E000056);
		}
		ProjectPO project = projectCache.get(projectId);
		String path = Tools.getStaticPath(project);
		if(project.getType() != ProjectType.PUBLIC.getType()){
			Tools.deleteFile(path);
			// 删除旧的静态化文件
			throw new MyException(MyError.E000044);
		}
		
		Map<String, Object> returnMap = getProjectModuleInfor(null, project, "-错误码");
		

		ErrorQuery errorQuery = new ErrorQuery().setProjectId(projectId);
		errorQuery.setCurrentPage(currentPage);
		Page page = new Page(errorQuery);
		List<Error> errorModels = errorService.query(errorQuery);
		page.setAllRow(errorService.count(errorQuery));

		returnMap.put("page", page);
		returnMap.put("errorList", ErrorAdapter.getDto(errorModels));
		returnMap.put("activePage","errorList");
		returnMap.put("url", "errorList");
		returnMap.put("needStaticizes", needStaticizes);
		return new ModelAndView("WEB-INF/views/staticize/default/errorList.jsp",returnMap);
	}

	

	/**
	 * 静态化接口列表
	 */
	@RequestMapping("/interfaceList.do")
	public ModelAndView interfaceList(HttpServletRequest req, @RequestParam String moduleId, @RequestParam int currentPage,
			String needStaticizes, @RequestParam String secretKey) throws MyException {
		// 验证是否是非法请求
		if( !settingCache.get(S_SECRETKEY).getValue().equals(secretKey) ){
			throw new MyException(MyError.E000056);
		}
		
		ModulePO module = moduleCache.get(moduleId);
		ProjectPO project = projectCache.get(module.getProjectId());
		String path = Tools.getStaticPath(project);

		if(project.getType() != ProjectType.PUBLIC.getType()){
			Tools.deleteFile(path);
			// 删除旧的静态化文件
			throw new MyException(MyError.E000044);
		}
		
		Map<String, Object> returnMap = getProjectModuleInfor(module, project, "-接口");
		
		Map<String, Object> map = Tools.getMap("moduleId", moduleId);

        InterfaceQuery interfaceQuery = new InterfaceQuery().setCurrentPage(currentPage).setModuleId(moduleId);
        Page page = new Page(interfaceQuery);
        page.setAllRow(interfaceService.count(interfaceQuery));
		returnMap.put("page", page);
		returnMap.put("interfaceList", InterfaceAdapter.getDto(interfaceService.query(interfaceQuery), module, null));
		returnMap.put("activePage",moduleId+"_interface");
		returnMap.put("url", module.getId() + "-interfaceList");
		returnMap.put("needStaticizes", needStaticizes);
		return new ModelAndView("WEB-INF/views/staticize/default/interfaceList.jsp",returnMap);
	}

	
	/**
	 * 静态化模块文档列表
	 */
	@RequestMapping("/articleList.do")
	public ModelAndView staticizeModule(HttpServletRequest req, @RequestParam String moduleId,@RequestParam String category,@RequestParam int currentPage,
			String type, String needStaticizes, @RequestParam String secretKey) throws MyException {
		// 验证是否是非法请求
		if( !settingCache.get(S_SECRETKEY).getValue().equals(secretKey) ){
			throw new MyException(MyError.E000056);
		}
		ModulePO module = moduleCache.get(moduleId);
		ProjectPO project = projectCache.get(module.getProjectId());
		String path = Tools.getStaticPath(project);

		if(project.getType() != ProjectType.PUBLIC.getType()){
			Tools.deleteFile(path);
			// 删除旧的静态化文件
			throw new MyException(MyError.E000044);
		}
		
		Map<String, Object> returnMap = getProjectModuleInfor(module, project, "-文档");
		
		// 当前类目
		if( category.equals(IConst.ALL) ){
			category = "";
			returnMap.put("md5Category", "");
		}else{
			returnMap.put("md5Category", MD5.encrytMD5(category, "").substring(0, 10));
		}
		
		if(MyString.isEmpty(type)){
			type = "ARTICLE";
		}
		
		if(type.equals("ARTICLE")){
			// 获取所有类目
			// 静态化模块文档
			List<String> categorys = moduleService.queryCategoryByModuleId(module.getId());
			List<CategoryDto> categoryDtos = new ArrayList<CategoryDto>();
			// 文档分类，按类目静态化
			for(String c: categorys){
				if(MyString.isEmpty(c)){
					continue;
				}
				CategoryDto categoryDto = new CategoryDto();
				categoryDto.setMd5Category(MD5.encrytMD5(c, "").substring(0, 10));
				categoryDto.setCategory(c);
				categoryDtos.add( categoryDto );
			}
			returnMap.put("categoryDtos", categoryDtos);
			returnMap.put("activePage",module.getId()+"_article");
			returnMap.put("url", module.getId() + "-articleList-"+returnMap.get("md5Category"));
		}else{
			returnMap.put("activePage",module.getId()+"_dictionary");
			returnMap.put("url", module.getId() + "-dictionary");
		}
		
		Map<String, Object> map = Tools.getMap("moduleId", moduleId, "type", type, "category", category);

        ArticleQuery articleQuery = new ArticleQuery().setCurrentPage(currentPage).setModuleId(moduleId).setType(type).setCategory(category);
        Page page = new Page(articleQuery);
        page.setAllRow(articleService.count(articleQuery));
		List<Article> articleList = articleService.query(articleQuery);
		returnMap.put("page", page);
		returnMap.put("articleList", articleList);
		returnMap.put("needStaticizes", needStaticizes);
		return new ModelAndView("WEB-INF/views/staticize/default/articleList.jsp",returnMap);
	}


	/**
	 * 静态化文档
	 * @param req
	 * @param articleId
	 * @return
	 * @throws MyException
	 */
	@RequestMapping("/articleDetail.do")
	public ModelAndView staticizeArticle(HttpServletRequest req, @RequestParam String articleId, 
			String needStaticizes, @RequestParam String secretKey) throws MyException {
		// 验证是否是非法请求
		if( !settingCache.get(S_SECRETKEY).getValue().equals(secretKey) ){
			throw new MyException(MyError.E000056);
		}		
		
		ArticleWithBLOBs article = articleService.getById(articleId);
		ModulePO module = moduleCache.get(article.getModuleId());
		ProjectPO project = projectCache.get(module.getProjectId());
		String path = Tools.getStaticPath(project);

		if(project.getType() != ProjectType.PUBLIC.getType()){
			Tools.deleteFile(path);
			// 删除旧的静态化文件
			throw new MyException(MyError.E000044);
		}
		if(article.getType().equals(ArticleType.ARTICLE.name())){
			Map<String, Object> returnMap = getProjectModuleInfor(module, project, "-文档详情");
			returnMap.put("article", article);
			// 项目备注将静态化成网站的description
			returnMap.put("description", article.getBrief());
			// 模块名称将静态化成网站标题
			returnMap.put("title", article.getName());

			returnMap.put("activePage",module.getId()+"_article");
			returnMap.put("needStaticizes", needStaticizes);
			return new ModelAndView("WEB-INF/views/staticize/default/articleDetail.jsp",returnMap);
		}else{
			Map<String, Object> returnMap = getProjectModuleInfor(module, project, "-数据库表详情");
			returnMap.put("article", article);
			returnMap.put("activePage",module.getId()+"_dictionary");
			returnMap.put("dictionaryFields", JSONArray.toArray(JSONArray.fromObject(article.getContent()), DictionaryDto.class));
			returnMap.put("needStaticizes", needStaticizes);
			return new ModelAndView("WEB-INF/views/staticize/default/dictionaryDetail.jsp",returnMap);
		}
	}
	
	/**
	 * 静态化接口详情
	 * @param req
	 * @return
	 * @throws MyException
	 */
	@RequestMapping("/interfaceDetail.do")
	public ModelAndView interfaceDetail(HttpServletRequest req, @RequestParam String interfaceId,
			String needStaticizes, @RequestParam String secretKey) throws MyException {
		// 验证是否是非法请求
		if( !settingCache.get(S_SECRETKEY).getValue().equals(secretKey) ){
			throw new MyException(MyError.E000056);
		}		
				
		InterfaceWithBLOBs interFace = interfaceService.getById(interfaceId);
		ModulePO module = moduleCache.get(interFace.getModuleId());
		ProjectPO project = projectCache.get(module.getProjectId());
		String path = Tools.getStaticPath(project);

		if(project.getType() != ProjectType.PUBLIC.getType()){
			Tools.deleteFile(path);
			// 删除旧的静态化文件
			throw new MyException(MyError.E000044);
		}

api/src/main/webapp/WEB-INF/views/staticize/default/articleDetail.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html lang="en">
<head>
	<%@ include  file="css.jsp"%>
</head>
<body class="s-bg-color">
	<!-- top navbar -->
	<%@ include  file="topNav.jsp"%>
	
	<div class="container p0 mt20">
		<div class="row min-h p0 m0">
			<!-- leftMenu -->
			<%@ include  file="left.jsp"%>
			<div  id="article-content" class="col-xs-12 col-md-9 p0 s-bg-color m0 pt0">
				<div class="BGFFF min-h500 p20">
					<div class="p3 pl10 pr10 mr10 f16 fb  mt10 mb10 adorn-bl-3">${article.name}</div>
					<div class="f14 mb10 pl20 C999 f12">
						${article.brief}
					</div>	
					<div class="f14 dashed-t pt20 imgCenter">${article.content}</div>
				</div>
			</div>
			
		</div>
	</div>
	<!-- footer -->
	<%@ include  file="footer.jsp"%>
	<script type="text/javascript">
	if($(window).width() < 1000){
		scrollToId('article-content');
	}
	</script>
</body>
</html>

api/src/main/webapp/WEB-INF/views/staticize/default/articleList.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html lang="en">
<head>
	<%@ include  file="css.jsp"%>
	<style type="text/css"> 
		.C${md5Category}{color:#ffffff; border:0px; background-color:${settings.ADORN_COLOR}!important;}
	</style>
	
</head>
<body class="s-bg-color">
	<!-- top navbar -->
	<%@ include  file="topNav.jsp"%>
	
	<div class="container p0 mt20">
		<div class="row min-h p0 m0">
			<!-- leftMenu -->
			<%@ include  file="left.jsp"%>
			<div class="col-xs-12 col-md-9 p0 s-bg-color m0 pt0">
				<div class="BGFFF min-h500 p20">
					<c:if test="${categoryDtos!=null}">
						<div class="col-xs-12 f14 pl0 mb10 pb5" id="article-content">
							<div class="fl mt2">文档筛选：</div>
							<c:forEach var="f" items="${categoryDtos}" varStatus="status"> 
								<a class="dis fl b1 p3 pl10 pr10 r12 mr10 f12 fn no_unl cursor C999 C${f.md5Category}" href="${module.id}-articleList-${f.md5Category}-1.html">${f.category}</a>
							</c:forEach>
						</div>
						<div class="cb"></div>
					</c:if>
					<c:if test="${categoryDtos==null}">
						<div class="col-xs-12 f16 pl10 fb mb10 adorn-bl-3" id="article-content">
							数据库表列表
						</div>
						<div class="cb"></div>
					</c:if>
					<c:if test="${articleList.size() == 0}">
						<div class="col-xs-12 tc mt10 mb10 C999">
									<i class="iconfont f20 mt-5 mr10">&#xe69c;</i>该模块下数据
						</div>
					</c:if>
					
					<c:forEach var="f" items="${articleList}" varStatus="status">
						<div class="dashed-t">
							<a href="${f.id}.html" class="p10 pl0 f16 fb dis w C000 no_unl">${f.name}</a>
							<div class ="f14 C555">${f.brief}</div>
							<div class="tr C999 f12 p10"><span class="C999 pl20">${f.createTime}</span></div>
						</div>
					</c:forEach>
					
					<%@ include file="page.jsp"%>
				
				</div>
			</div>
			
		</div>
	</div>

	<!-- footer -->
	<%@ include  file="footer.jsp"%>
	<script type="text/javascript">
		if($(window).width() < 1000){
			scrollToId('article-content');
		}
	</script>
</body>
</html>

api/src/main/webapp/WEB-INF/views/staticize/default/css.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="${keywords}" />
	<meta name="description" content="${description}" />
	<link href="${settings.ICON}" rel="shortcut icon" type="image/x-icon" />
	<link href="${settings.ICON}" rel="icon" type="image/x-icon" />
	<link href="${settings.ICON}" rel="shortcut" type="image/x-icon" />
	<link href="../../resources/framework/bootstrap-3.0.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="../../resources/framework/bootstrap-3.0.0/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css" />
	<!-- base-min.css,admin.css应该发在bootstrap之后,覆盖部分bootstrap样式 -->
	<link href="../../resources/css/allCss.css" rel="stylesheet" type="text/css" />
	<title>${title}</title>
<!-- TODO 样式提取到setting.css中-->
<style type="text/css"> 
body{overflow-x:hidden;}
@media ( min-width : 1210px) {.container {width: {{settings.MAX_WIDTH}}px!important}}
@media ( max-width : 992px) {.col-md-mr0 {margin-right:0px!important}}
pre { white-space: normal;}

/********前端显示最小宽度*************/
.container-fluid{min-width: 400px;}
.navbar-inverse{min-width: 400px;border:0px!important;}
.container{min-width: 400px;}   
.C${module.id}{color:${settings.ADORN_COLOR}!important;font-weight:bold;}
.C${activePage}{color:${settings.ADORN_COLOR}!important;font-weight:bold;}
.s-bg-color {background-color: ${settings.BG_COLOR}}
.s-nav-bg-color {background-color: ${settings.NAV_BG_COLOR}!important}
.s-nav-color {color: ${settings.NAV_COLOR}}
.s-nav-color a {color: ${settings.NAV_COLOR}}
/* 默认主色:#B768A5*/
.main-bg {background-color: ${settings.MAIN_COLOR}!important;}
.main-color {color: ${settings.MAIN_COLOR}}
.adorn-color {color: ${settings.ADORN_COLOR}}
.adorn-bl-3{ border-left:3px solid ${settings.ADORN_COLOR}}
.adorn-bb-1{ border-bottom:1px solid ${settings.ADORN_COLOR}}
.adorn-color:hover {color: ${settings.ADORN_COLOR}}
.adorn-bg {background-color: ${settings.ADORN_COLOR}}
.interface-detail blockquote {color: ${settings.MAIN_COLOR}}
.bt-5 {border-top: 5px solid${settings.MAIN_COLOR}}
.bl-5 {border-left: 5px solid${settings.MAIN_COLOR}}
.menu_a:hover {background-color: ${settings.MAIN_COLOR}!important;color:#ffffff!important;opacity:1;}
.iactive {background-color: ${settings.MAIN_COLOR}!important;color:#ffffff!important;opacity: 0.8;}
.look-up-content {border-top: 3px solid${settings.MAIN_COLOR};}
.sk-wave .sk-rect {background-color: ${settings.MAIN_COLOR};}
.btn-adorn {
  color: #ffffff;
  background-color:${settings.ADORN_COLOR};
}
.btn-adorn:hover{
  color: #ffffff;
  background-color: ${settings.ADORN_COLOR};
  opacity: 0.8;
}
.btn-main {
  color: #ffffff;
  background-color:${settings.MAIN_COLOR};
}
.btn-main:hover{
  color: #ffffff;
  background-color: ${settings.MAIN_COLOR};
  opacity: 0.8;
}
ul{list-style-type:circle;}
<% Map<String,String> settings = (Map<String,String>)request.getAttribute("settings");%>
.login-bg{background: url('<%=settings.get("LOGINBG").startsWith("http")? settings.get("LOGINBG"):basePath + settings.get("LOGINBG")%>') 50% 50% / cover no-repeat fixed;}
.title-bg-img{
	background-image:url('<%=settings.get("TITLEBG").startsWith("http")? settings.get("TITLEBG"):basePath + settings.get("TITLEBG")%>')!important; background-position:center;
}
/****************End:颜色*****************/
/****************字体*********************/
body, h1, h2, h3, h4, h5, h6, hr, blockquote, dl, dt, dd, ul, ol, li,
	pre, form, fieldset, legend, button, input, textarea, th, td {
	font-family: ${settings.FONT_FAMILY};}
}
</style>

api/src/main/webapp/WEB-INF/views/staticize/default/dictionaryDetail.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html lang="en">
<head>
	<%@ include  file="css.jsp"%>
</head>
<body class="s-bg-color">
	<!-- top navbar -->
	<%@ include  file="topNav.jsp"%>
	
	<div class="container p0 mt20">
		<div class="row min-h p0 m0">
			<!-- leftMenu -->
			<%@ include  file="left.jsp"%>
			<div  id="article-content" class="col-xs-12 col-md-9 p0 s-bg-color m0 pt0">
				<div class="BGFFF min-h500 p20">
					<div class="p3 pl10 pr10 mr10 f16 fb  mt10 mb10 adorn-bl-3">${article.name}</div>
					<div class="f14 mb10 pl20 C999 f12">
						${article.brief}
					</div>	
					<table class="table table-bordered f12 C555 mb5">
					<tr class="main-bg CFFF">
						<th class="w200">字段</th>
						<th  class="w150">类型</th>
						<th  class="w50">空</th>
						<th  class="w150">默认</th>
						<th  class="w50">标识</th>
						<th  class="w200">注释</th>
					</tr>
						<c:forEach var="f" items="${dictionaryFields}" varStatus="status">
						<tr>
							<td>${f.name}</td>
							<td>${f.type}</td>
							<td>${f.notNull=='true'?'是':'否'}</td>
							<td>${f.def}</td>
							<td class="dic-bg-${f.flag}">${f.flag}</td>
							<td>${f.remark}</td>
						</tr>
						</c:forEach>
					</table>
				</div>
			</div>
			
		</div>
	</div>
	<!-- footer -->
	<%@ include  file="footer.jsp"%>
	<script type="text/javascript">
	if($(window).width() < 1000){
		scrollToId('article-content');
	}
	$(".dic-bg-primary").addClass("bg-danger");
	$(".dic-bg-primary").html("主键");
	$(".dic-bg-foreign").addClass("bg-success");
	$(".dic-bg-foreign").html("外键");
	$(".dic-bg-associate").addClass("bg-info");
	$(".dic-bg-associate").html("关联");
	$(".dic-bg-common").html("普通");
	</script>
</body>
</html>

api/src/main/webapp/WEB-INF/views/staticize/default/errorList.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html lang="en">
<head>
	<%@ include  file="css.jsp"%>
</head>
<body class="s-bg-color">
	<!-- top navbar -->
	<%@ include  file="topNav.jsp"%>
	
	<div class="container p0 mt20">
		<div class="row min-h p0 m0">
			<!-- leftMenu -->
			<%@ include  file="left.jsp"%>
			<div class="col-xs-12 col-md-9 p0 s-bg-color m0 pt0">
				<div class="BGFFF min-h500 p20">
					<div class="col-xs-12 f14 pl10 mb10 adorn-bl-3" id="error-content">
						错误码列表
					</div>
					<c:if test="${errorList.size() == 0}">
						<div class="col-xs-12 tc mt10 mb10 C999">
									<i class="iconfont f20 mt-5 mr10">&#xe69c;</i>该模块下没有错误码
						</div>
					</c:if>
					
						
					<c:if test="${errorList.size() > 0}">	
						<div class="col-xs-12 p0" >
							<table class="table f12 table-hover">
								<thead>
									<tr class="main-bg f14 CFFF">
										<th class="tc w100">Code</th>
										<th class="tc">Msg</th>
										<th class="tc w150">项目</th>
									</tr>
								</thead>
								<tbody>
									<c:forEach var="f" items="${errorList}" varStatus="status">
										<tr>
											<td class="tc p12">${f.errorCode}</td>
											<td class="tc p12">${f.errorMsg}</td>
											<td class="tc p12">${f.projectName}</td>
										</tr>
									</c:forEach>
								</tbody>
							</table>
						</div>
					</c:if>
					<%@ include file="page.jsp"%>
				
				</div>
			</div>
			
		</div>
	</div>

	<!-- footer -->
	<%@ include  file="footer.jsp"%>
	<script type="text/javascript">
		if($(window).width() < 1000){
			scrollToId('error-content');
		}
	</script>
</body>
</html>

api/src/main/webapp/WEB-INF/views/staticize/default/footer.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
		<div class="p0 m0 mt30 def-bg w s-nav-bg-color s-nav-color">
			<div class="container p0">
				<div class="row p0 m0">
					<div class="col-xs-12 f12 p0 mb5 tl mt30 mb50 pl20">
						©crap.cn&nbsp; 本系统由<a href="http://crap.cn" target="_blank">CrapApi</a>开源项目生成
		
					<div class="mt20">
						友情链接：
						<ul class="dis-in-tab p0">
							<li class="dis-in-tab pr20">
								<a target="_blank"
									href="https://github.com/EhsanTang/CrapApi">源码:GitHub</a>
							</li>
							<li  class="dis-in-tab pr20">
								<a target="_blank"
									href="https://gitee.com/CrapApi/CrapApi">源码:码云</a>
							</li>
							<li  class="dis-in-tab pr20">
								<a target="_blank"
									href="http://api.crap.cn">开源API接口管理系统</a>
							</li>
							<li  class="dis-in-tab pr20">
								<a href="javascript:void(0)">粤ICP备15091896号-1</a>
							</li>
						</ul>
					</div>
		
				</div>
			</div>
		</div>
	</div>
	
	<div id="go_top" onclick="goTop()" style="padding-top: 9px; padding-left: 13px;"
		class="cursor">
		<i class="iconfont f20" style="color: #FFF;">&#xe617;</i>
	</div>
	<script src="../../resources/framework/jquery-1.9.1.min.js"></script>
	<script src="../../resources/framework/bootstrap-3.0.0/js/bootstrap.min.js"></script>
	<script src="../../resources/js/global.js"></script>
	<script src="../../resources/js/crapApi.js"></script>